import asyncio
from typing import Any, Dict
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnableConfig
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent

from config import config
from models import IntentDecision

class LLMServer:
    def __init__(self):
        self.API_KEY = config.LLM_API_KEY
        self.MODEL = config.LLM_MODEL_NAME
        self.API_URL = config.LLM_API_URL
        self.MCP_SERVER_URL = config.MCP_SERVER_URL
        self.MCP_SERVER_API_KEY = config.MCP_SERVER_API_KEY

        self._agent = None
        self._mcp_client = None
        self.memory = MemorySaver()
        self._init_lock = asyncio.Lock()

        self.SYSTEM_PROMPT = """
            You are a precise, autonomous operational executor connected to an MCP tool server. 
            Your sole task is to receive a structured JSON decision payload, invoke the exact MCP tool specified, and output only the direct result.

            ### CORE OBJECTIVES & EXECUTION PIPELINE
            1. Parse the Decision Payload:
            - You will receive a structured JSON object (from the Gatekeeper) containing the execution routing.
            - Read the `intended_action` field to identify the exact MCP tool to execute.
            - Read the `action_parameters` field to obtain the exact arguments required for the tool.

            2. MCP Tool Execution:
            - Do not attempt to extract new entities, infer intent, or analyze the user's raw conversation. The Gatekeeper's routing decision is final.
            - Immediately invoke the tool specified in `intended_action` using exclusively the arguments mapped in `action_parameters`.

            3. Output Delivery:
            - Once the tool execution is complete, your final response must consist SOLELY of the exact output/data payload returned by that tool.

            ### STRICT OPERATIONAL CONSTRAINTS (ZERO-TOLERANCE RULES)
            - NO CONVERSATIONAL FILLER: Never include conversational intros, outros, or status updates (e.g., do NOT say "Here is the data:", "Executing tool...", "Execution successful:", or "I found the following:").
            - NO SECOND-GUESSING: Do not alter, infer, or validate the parameters provided in the JSON payload. Execute exactly what is passed.
            - NO CLARIFICATIONS: Do not ask follow-up questions. If the tool fails or errors, return the raw error output directly.
            - NO RECOMMENDATIONS OR OPINIONS: Do not provide suggestions, analysis, commentary, or next-step advice based on the tool's output.
            - RAW RESULTS ONLY: Output the exact data, table, JSON, or report generated by the tool without altering its contents or wrapping it in narrative prose.
        """.strip()

    async def _get_or_create_agent(self):
        if self._agent is not None:
            return self._agent

        async with self._init_lock:
            if self._agent is not None:
                return self._agent

            self._mcp_client = MultiServerMCPClient({
                "rtd_tools": {
                    "url": self.MCP_SERVER_URL,
                    "transport": "http",
                    "headers": {
                        "Authorization": f"Bearer {self.MCP_SERVER_API_KEY}"
                    }
                }
            })
            tools = await self._mcp_client.get_tools()

            llm = ChatOpenAI(
                model=self.MODEL,
                base_url=self.API_URL,
                api_key=self.API_KEY,
                temperature=0.0,
                max_retries=5,
                timeout=60,
            )

            self._agent = create_react_agent(
                model=llm,
                tools=tools,
                prompt=self.SYSTEM_PROMPT,
                checkpointer=self.memory
            )
            return self._agent

    async def get_mcp_tools(self) -> list:
        """
        Safely fetches MCP tools for external services like the Gatekeeper.
        Initializes the client and agent if they haven't been built yet.
        """
        if self._mcp_client is None:
            await self._get_or_create_agent()
        return await self._mcp_client.get_tools()

    async def serve(self, decision: IntentDecision, chat_id: str) -> str:
        agent = await self._get_or_create_agent()
        run_config: RunnableConfig = {"configurable": {"thread_id": f"rtd_{chat_id}"}}
        payload_str = decision.model_dump_json(indent=2)

        response: Dict[str, Any] = await agent.ainvoke(
            input={
                "messages": [{
                    "role": "user",
                    "content": f"Execute action payload:\n{payload_str}"
                    }]
            },
            config=run_config
        )
        return response["messages"][-1].content

llm_server = LLMServer()