import asyncio
from typing import Any, Dict
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.runnables import RunnableConfig
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent

from config import config


class LLMServer:
    def __init__(self):
        self.API_KEY = config.LLM_API_KEY
        self.MODEL = config.LLM_MODEL_NAME
        self.API_URL = config.LLM_API_URL

        self.MCP_SERVER_URL = config.MCP_SERVER_URL
        self.MCP_SERVER_TRANSPORT = config.MCP_SERVER_TRANSPORT
        self.MCP_SERVER_API_KEY = config.MCP_SERVER_API_KEY

        self._agent = None
        self._mcp_client = None

        self.memory = MemorySaver()
        self._init_lock = asyncio.Lock()

        self.SYSTEM_PROMPT = """
            You are a precise, autonomous operational agent connected to an MCP tool server. Your sole task is to process incoming conversation logs, extract required attributes, invoke the appropriate MCP tool, and output only the direct result.

            ### CORE OBJECTIVES & EXECUTION PIPELINE
            1. Analyze & Understand:
            - Carefully review the user input/conversation history to determine the user's explicit intent and operational domain.

            2. Attribute Extraction:
            - Identify and extract all required operational entities, parameters, and filters (e.g., district, tenure, region, prices, sizes, MRTs, etc.).
            - Normalize these attributes to match the exact schema and data types expected by the available MCP tools.

            3. MCP Tool Selection & Execution:
            - Map the identified intent and extracted attributes to the most suitable tool available on the MCP server.
            - Execute the tool call using only the factual data extracted from the conversation.

            4. Output Delivery:
            - Once the tool execution is complete, your final response must consist SOLELY of the output/data payload returned by that tool.

            ### STRICT OPERATIONAL CONSTRAINTS (ZERO-TOLERANCE RULES)
            - NO CONVERSATIONAL FILLER: Never include conversational intros, outros, or status updates (e.g., do NOT say "Here is your report:", "Based on the tool output...", "Execution successful:", or "I found the following:").
            - NO CLARIFICATION QUESTIONS: Do not ask follow-up questions, request missing details, or prompt the user for input under any circumstance.
            - NO RECOMMENDATIONS OR OPINIONS: Do not provide suggestions, analysis, commentary, or next-step advice.
            - RAW RESULTS ONLY: Output the exact data, table, JSON, or report generated by the tool without altering its contents or wrapping it in narrative prose.
        """.strip()

    async def _get_or_create_agent(self):
        """Builds the agent once and caches it in memory."""
        if self._agent is not None:
            return self._agent

        async with self._init_lock:
            if self._agent is not None:
                return self._agent

            self._mcp_client = MultiServerMCPClient({
                "utility_tools": {
                    "url": self.MCP_SERVER_URL,
                    "transport": "http",
                    "headers": {
                        "Authorization": f"Bearer {self.MCP_SERVER_API_KEY}"
                    },
                }
            })
            tools = await self._mcp_client.get_tools()

            llm = ChatOpenAI(
                model=self.MODEL,
                base_url=self.API_URL,
                api_key=self.API_KEY,
                temperature=0.0,
                max_retries=3,
                timeout=60,
            )

            self._agent = create_agent(
                model=llm,
                tools=tools,
                system_prompt=self.SYSTEM_PROMPT,
                checkpointer=self.memory,
            )
            return self._agent

    async def get_mcp_tools(self) -> list:
        """
        Safely fetches MCP tools for external services like the Gatekeeper.
        Initializes the client and agent if they haven't been built yet.
        """
        # Ensure the client and agent are built
        if self._mcp_client is None:
            await self._get_or_create_agent()
            
        # Safely return the tools
        return await self._mcp_client.get_tools()

    def build_chat_per_user(self, chat_id: str) -> RunnableConfig:
        """Synchronous configuration builder."""
        return {
            "configurable": {
                "thread_id": f"tenant_user_{chat_id}"
            }
        }

    async def serve(self, query: str, chat_id: str) -> str:
        agent = await self._get_or_create_agent()
        config = self.build_chat_per_user(chat_id=chat_id)

        response: Dict[str, Any] = await agent.ainvoke(
            input={
                "messages": [{
                    "role": "user",
                    "content": query
                    }]
                },
            config=config,
        )

        return response["messages"][-1].content

llm_server = LLMServer()